### ISSUE TITLE
General question regarding workflow 

### ISSUE THREAD

**Issue by Opussci** [quantum-journal/o3po#172] opened 2020-03-29 12:29 UTC
Hello, firstly I would like to say that this plugin seems to be the best implementation of scholarly publishing for WP.
My question is general one.
Is this plugin applicable to other journals, ones not closely connected to the Arxiv as quantum is?

**Comment by cgogolin** [comment] 2020-03-29 13:06
With some adjustments, such as adding the ability to upload the full text pdf and latex source from the local computer, it should be adoptable to non-arxiv-overlay publishing.

**Comment by Opussci** [comment] 2020-03-29 13:14
Thank you for fast response.
You do not think WordPress pdf upload would work?

**Comment by Opussci** [comment] 2020-03-29 13:15
I am editor in chief assistant if one small academy-led journal. We use OJS at the moment but it is just too conservative platform for publishing.

**Comment by cgogolin** [comment] 2020-03-29 15:26
The issue is more that there would have to be way to make O-3PO use a manually uploaded pdf as the full text pdf instead of one automatically downloaded by O-3PO from the arxiv. If you have basic knowledge of the PHP programming it shouldn't be hard to add such an option and I would be happy to accept a pull request for it to incorporate it into the official code base.

**Comment by Opussci** [comment] 2020-03-29 16:23
I see, but does it need full pdf/tex file, for the metadata maybe? My goal would be to use HTML for full text. As I could see you have all meta tags needed for Google Scholar indexing in the HTML already.
Are maybe reference pulled from tex file?
How do you style references in the HTML, with citation.js or you use something else?
We would continue to use OJS for review.

**Comment by Opussci** [comment] 2020-03-29 18:36
Just from my curiosity if I can ask why did you choose WordPress in the first place? Ojs is also written in the PHP? It is good choose, in my view that you use WordPress.

**Comment by cgogolin** [comment] 2020-03-30 06:44
Well, you somehow have to get the meta-data into the system first. O-3PO does that mostly automagically by extracting that data form the tex soure code and the arXiv abstract page.

O-3PO has a the notion of a "secondary journal" (we use it for [Quantum Views](https://quantum-journal.org/views/)) which has html only articles. You could only use the secondary journal or O-3PO. Again this would require some adjustments to the code.

O-3PO is for ublishing only. The peer-review needs to be organized with a different platform. We use Scholastica for that but you can equally use OJS.

We were not happy with any of the existing publishing platforms and thus decided to write our own.

**Comment by Opussci** [comment] 2020-03-31 20:59
I entirely agree with your opinion regarding existing publishing platforms. I see that you have made a very adequate publishing platform with highwire meta tags. For Google Scholar discoverability. Dublin Core and prisms tags could also be added to expand it in the future and completely mirror professional platforms.
I suppose you insert metadata by some kind of form for the HTML articles, since reading pdf file is harder than reading tex files, that workflow with form could also work for pdf files? 
My opinion is that O-3PO could be embraced in scientific publishing. 
There are more platforms for scientific publishing nowadays than there was 4 years ago when you launched your journal, e.g. Janeway, PubPub, and work of Coko foundation but they all repeat OJS mistakes in not separating peer review and publishing.
Peer reviews should always be separated from the publishing site. That is one of the major shortcomings with the OJS, hence, OJS is only good for peer review.
I could add pdf upload functionality sometime in the future, I must complete my Ph.D. thesis first. If you can give me guidance in the process I would be willing to accept that.

**Comment by cgogolin** [comment] 2020-04-18 12:28
I am closing this as it is not really an "issue" with O-3PO.

**Closed by cgogolin** 2020-04-18 12:28 UTC
